<a href="https://colab.research.google.com/github/ifte110/tensorflow-deep-learning-0toM-Self-Practice/blob/main/00_tf_found.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector.ndim

1

In [ ]:
from numpy import float32
tensor = tf.constant([[[5,10,6],
                     [7,1,8]],
                     [[6,5,3],
                     [5,9,6]]],dtype=float32)
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 5., 10.,  6.],
        [ 7.,  1.,  8.]],

       [[ 6.,  5.,  3.],
        [ 5.,  9.,  6.]]], dtype=float32)>

In [ ]:
Vartensor = tf.Variable([10,10])

Vartensor[1].assign(50)

Vartensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 50], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.uniform(shape=(3,3))
random_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794],
       [0.49039817, 0.1889317 , 0.52027524],
       [0.8736881 , 0.46921718, 0.63932586]], dtype=float32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(tensor)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 6.,  5.,  3.],
        [ 5.,  9.,  6.]],

       [[ 5., 10.,  6.],
        [ 7.,  1.,  8.]]], dtype=float32)>

In [ ]:
import numpy as np
numpy_a = np.arange(1,25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_a, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
rank4 = tf.random.uniform(shape=[2,3,4,5], dtype=float32)
rank4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396],
         [0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256],
         [0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ],
         [0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ]],

        [[0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ],
         [0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ],
         [0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784],
         [0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097]],

        [[0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176],
         [0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
         [0.20301068, 0.11448455, 0.35100245, 0.68227184, 0.18108869],
         [0.8163481 , 0.65651655, 0.9258256 , 0.2391715 , 0.8365958 ]]],


       [[[0.04765272, 0.8007157 , 0.8299267 , 0.14328372, 0.8616878 ],
         [0.970

In [ ]:
rank4[:,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883],
         [0.89256823, 0.94674826]],

        [[0.13803864, 0.12217975],
         [0.59708476, 0.6109482 ]]],


       [[[0.04765272, 0.8007157 ],
         [0.9707202 , 0.6779593 ]],

        [[0.14919603, 0.8594816 ],
         [0.70333743, 0.5343715 ]]]], dtype=float32)>

In [ ]:
rank2 = tf.constant([[10,7],
                     [5,6]])
rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6]], dtype=int32)>

In [ ]:
rank2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6], dtype=int32)>

In [ ]:
rank3 = rank2[...,tf.newaxis]
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 5,  6]]], dtype=int32)>

In [ ]:
import tensorflow as tf

a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])
#tf.matmul(a, b)
tf.tensordot(a, b, axes=0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4]]]], dtype=int32)>

In [ ]:
a = tf.cast(rank4, dtype=tf.float16)
a.dtype

tf.float16

In [ ]:
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([74, 64, 97, 51, 56, 39, 61, 56, 31,  4, 41, 81, 45, 67,  3, 40, 65,
        3, 12, 45, 75, 24, 79, 87, 55, 70, 24, 93, 68, 31, 32, 31, 57,  5,
       10, 87,  9, 15, 53, 93, 33, 74, 58, 22, 96, 55, 63, 50, 87, 16])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2487>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=751>

In [ ]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.39475>

In [ ]:
tf.random.set_seed(42)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_min(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
some_list = [0,1,2,3]
tf.one_hot(some_list,depth=4, on_value="a denial", off_value="teen spirit")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'a denial', b'teen spirit', b'teen spirit', b'teen spirit'],
       [b'teen spirit', b'a denial', b'teen spirit', b'teen spirit'],
       [b'teen spirit', b'teen spirit', b'a denial', b'teen spirit'],
       [b'teen spirit', b'teen spirit', b'teen spirit', b'a denial']],
      dtype=object)>

In [ ]:
tf.math.sqrt(tf.cast(f, dtype=float32))

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.81520677, 0.6640834 , 0.59403914, 0.6815296 , 0.18346775,
       0.8274493 , 0.8603008 , 0.9340474 , 0.4757377 , 0.47243714,
       0.55712485, 0.8499034 , 0.36494818, 0.74031335, 0.7580296 ,
       0.9485165 , 0.09728138, 0.7219631 , 0.796583  , 0.44646198,
       0.8540623 , 0.7388062 , 0.32797185, 0.82262146, 0.81257385,
       0.5804743 , 0.7755112 , 0.45893982, 0.9234377 , 0.66379344,
       0.9739238 , 0.48736632, 0.90099555, 0.72549254, 0.7030704 ,
       0.4648962 , 0.91963017, 0.93374735, 0.5553253 , 0.8287363 ,
       0.4874837 , 0.88415086, 0.98343194, 0.26210994, 0.89372224,
       0.8125805 , 0.766258  , 0.40573013, 0.85912883, 0.5661629 ],
      dtype=float32)>

In [ ]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]